package com.tyssSpark.recrutounitservice.repo;

import com.tyssSpark.recrutounitservice.dto.HrUnitData;
import com.tyssSpark.recrutounitservice.dto.HrUnitResponse;
import com.tyssSpark.recrutounitservice.dto.TraineeData;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import java.time.LocalDate;
import java.util.List;


@Repository
public interface HrUnitRepo extends JpaRepository<HrUnitData,Integer> {

    @Query("select new com.tyssSpark.recrutounitservice.dto.HrUnitResponse(bench.benMonth,bench.benSource,bench.benGender,bench.benBench,bench.benBatch,bench.benTraineeDuration,bench.benSkillSet,bench.benCtc,bench.benRevicedCtc,bench.benRemarks,hr.traineeOfficialId,hr.traineeOnBoardingDate,hr.hrName,hr.traineeDOB,hr.traineeFatherName,hr.traineeLocation,hr.traineeOfficialMailId,hr.traineePermanentAddress,hr.traineeJoiningFormalities,hr.traineeLOIFormalities,hr.traineeNDAFormalities,hr.traineeMarksCardDetails,hr.traineeBioMetricStatus,hr.traineeICards,hr.traineeRemarks,master.traineeName,master.traineeEmailId,master.traineeMobileNum,master.traineeStatus,master.traineeYearOfExp) from BenchUnitData bench, HrUnitData hr,TraineeData master where hr.traineeData.id = master.id and bench.traineeData.id = master.id ORDER BY bench.benMonth DESC")
    public List<HrUnitResponse> getAllDataFromAllTable();

    HrUnitData findByTraineeData(TraineeData masterDataInfo);

    HrUnitData findByTraineeOfficialId(String traineeOfficialId);

    @Query("select new com.tyssSpark.recrutounitservice.dto.HrUnitResponse(bench.benMonth,bench.benSource,bench.benGender,bench.benBench,bench.benBatch,bench.benTraineeDuration,bench.benSkillSet,bench.benCtc,bench.benRevicedCtc,bench.benRemarks,hr.traineeOfficialId,hr.traineeOnBoardingDate,hr.hrName,hr.traineeDOB,hr.traineeFatherName,hr.traineeLocation,hr.traineeOfficialMailId,hr.traineePermanentAddress,hr.traineeJoiningFormalities,hr.traineeLOIFormalities,hr.traineeNDAFormalities,hr.traineeMarksCardDetails,hr.traineeBioMetricStatus,hr.traineeICards,hr.traineeRemarks,master.traineeName,master.traineeEmailId,master.traineeMobileNum,master.traineeStatus,master.traineeYearOfExp) from BenchUnitData bench, HrUnitData hr,TraineeData master where hr.traineeData.id = master.id and bench.traineeData.id = master.id and bench.benMonth = :benMonth and master.traineeStatus = :employeeStatus and bench.benBench = :benBench")
    List<HrUnitResponse> getHrDataByMonthStatusBench(LocalDate benMonth, String employeeStatus, String benBench);

    @Query("select new com.tyssSpark.recrutounitservice.dto.HrUnitResponse(bench.benMonth,bench.benSource,bench.benGender,bench.benBench,bench.benBatch,bench.benTraineeDuration,bench.benSkillSet,bench.benCtc,bench.benRevicedCtc,bench.benRemarks,hr.traineeOfficialId,hr.traineeOnBoardingDate,hr.hrName,hr.traineeDOB,hr.traineeFatherName,hr.traineeLocation,hr.traineeOfficialMailId,hr.traineePermanentAddress,hr.traineeJoiningFormalities,hr.traineeLOIFormalities,hr.traineeNDAFormalities,hr.traineeMarksCardDetails,hr.traineeBioMetricStatus,hr.traineeICards,hr.traineeRemarks,master.traineeName,master.traineeEmailId,master.traineeMobileNum,master.traineeStatus,master.traineeYearOfExp) from BenchUnitData bench, HrUnitData hr,TraineeData master where hr.traineeData.id = master.id and bench.traineeData.id = master.id and hr.traineeBioMetricStatus = :hrTraineebiometricStatus and hr.traineeICards = :hrTraineeIcards")
    List<HrUnitResponse> getHrDataByBiometricStatusAndIcards(String hrTraineebiometricStatus, String hrTraineeIcards);

    @Query("select new com.tyssSpark.recrutounitservice.dto.HrUnitResponse(bench.benMonth,bench.benSource,bench.benGender,bench.benBench,bench.benBatch,bench.benTraineeDuration,bench.benSkillSet,bench.benCtc,bench.benRevicedCtc,bench.benRemarks,hr.traineeOfficialId,hr.traineeOnBoardingDate,hr.hrName,hr.traineeDOB,hr.traineeFatherName,hr.traineeLocation,hr.traineeOfficialMailId,hr.traineePermanentAddress,hr.traineeJoiningFormalities,hr.traineeLOIFormalities,hr.traineeNDAFormalities,hr.traineeMarksCardDetails,hr.traineeBioMetricStatus,hr.traineeICards,hr.traineeRemarks,master.traineeName,master.traineeEmailId,master.traineeMobileNum,master.traineeStatus,master.traineeYearOfExp) from BenchUnitData bench, HrUnitData hr,TraineeData master where hr.traineeData.id = master.id and bench.traineeData.id = master.id and master.traineeStatus = :employeeStatus")
    List<HrUnitResponse> getHRDataByStatusGreaterThan5Months(String employeeStatus);

        @Query("select new com.tyssSpark.recrutounitservice.dto.HrUnitResponse(bench.benMonth,bench.benSource,bench.benGender,bench.benBench,bench.benBatch,bench.benTraineeDuration,bench.benSkillSet,bench.benCtc,bench.benRevicedCtc,bench.benRemarks,hr.traineeOfficialId,hr.traineeOnBoardingDate,hr.hrName,hr.traineeDOB,hr.traineeFatherName,hr.traineeLocation,hr.traineeOfficialMailId,hr.traineePermanentAddress,hr.traineeJoiningFormalities,hr.traineeLOIFormalities,hr.traineeNDAFormalities,hr.traineeMarksCardDetails,hr.traineeBioMetricStatus,hr.traineeICards,hr.traineeRemarks,master.traineeName,master.traineeEmailId,master.traineeMobileNum,master.traineeStatus,master.traineeYearOfExp) from BenchUnitData bench, HrUnitData hr,TraineeData master where hr.traineeData.id = master.id and bench.traineeData.id = master.id and hr.traineeJoiningFormalities= :hrTraineeJoining")
    List<HrUnitResponse> getHrDataByTraineeJoining(String hrTraineeJoining);

    @Query("select new com.tyssSpark.recrutounitservice.dto.HrUnitResponse(bench.benMonth,bench.benSource,bench.benGender,bench.benBench,bench.benBatch,bench.benTraineeDuration,bench.benSkillSet,bench.benCtc,bench.benRevicedCtc,bench.benRemarks,hr.traineeOfficialId,hr.traineeOnBoardingDate,hr.hrName,hr.traineeDOB,hr.traineeFatherName,hr.traineeLocation,hr.traineeOfficialMailId,hr.traineePermanentAddress,hr.traineeJoiningFormalities,hr.traineeLOIFormalities,hr.traineeNDAFormalities,hr.traineeMarksCardDetails,hr.traineeBioMetricStatus,hr.traineeICards,hr.traineeRemarks,master.traineeName,master.traineeEmailId,master.traineeMobileNum,master.traineeStatus,master.traineeYearOfExp) from BenchUnitData bench, HrUnitData hr,TraineeData master where hr.traineeData.id = master.id and bench.traineeData.id = master.id and bench.benBench=:benBench")
    List<HrUnitResponse> getHrDataByBenBench(String benBench);

    @Query("select new com.tyssSpark.recrutounitservice.dto.HrUnitResponse(bench.benMonth,bench.benSource,bench.benGender,bench.benBench,bench.benBatch,bench.benTraineeDuration,bench.benSkillSet,bench.benCtc,bench.benRevicedCtc,bench.benRemarks,hr.traineeOfficialId,hr.traineeOnBoardingDate,hr.hrName,hr.traineeDOB,hr.traineeFatherName,hr.traineeLocation,hr.traineeOfficialMailId,hr.traineePermanentAddress,hr.traineeJoiningFormalities,hr.traineeLOIFormalities,hr.traineeNDAFormalities,hr.traineeMarksCardDetails,hr.traineeBioMetricStatus,hr.traineeICards,hr.traineeRemarks,master.traineeName,master.traineeEmailId,master.traineeMobileNum,master.traineeStatus,master.traineeYearOfExp) from BenchUnitData bench, HrUnitData hr,TraineeData master where hr.traineeData.id = master.id and bench.traineeData.id = master.id and hr.traineeLOIFormalities = :hrTraineeLoi")
    List<HrUnitResponse> getHrDataByTraineeLOIFormalities(String hrTraineeLoi);

    @Query("select new com.tyssSpark.recrutounitservice.dto.HrUnitResponse(bench.benMonth,bench.benSource,bench.benGender,bench.benBench,bench.benBatch,bench.benTraineeDuration,bench.benSkillSet,bench.benCtc,bench.benRevicedCtc,bench.benRemarks,hr.traineeOfficialId,hr.traineeOnBoardingDate,hr.hrName,hr.traineeDOB,hr.traineeFatherName,hr.traineeLocation,hr.traineeOfficialMailId,hr.traineePermanentAddress,hr.traineeJoiningFormalities,hr.traineeLOIFormalities,hr.traineeNDAFormalities,hr.traineeMarksCardDetails,hr.traineeBioMetricStatus,hr.traineeICards,hr.traineeRemarks,master.traineeName,master.traineeEmailId,master.traineeMobileNum,master.traineeStatus,master.traineeYearOfExp) from BenchUnitData bench, HrUnitData hr,TraineeData master where hr.traineeData.id = master.id and bench.traineeData.id = master.id and hr.traineeNDAFormalities = :hrTraineeNda")
    List<HrUnitResponse> getHrDataByTraineeNDAFormalities(String hrTraineeNda);

    @Query("select new com.tyssSpark.recrutounitservice.dto.HrUnitResponse(bench.benMonth,bench.benSource,bench.benGender,bench.benBench,bench.benBatch,bench.benTraineeDuration,bench.benSkillSet,bench.benCtc,bench.benRevicedCtc,bench.benRemarks,hr.traineeOfficialId,hr.traineeOnBoardingDate,hr.hrName,hr.traineeDOB,hr.traineeFatherName,hr.traineeLocation,hr.traineeOfficialMailId,hr.traineePermanentAddress,hr.traineeJoiningFormalities,hr.traineeLOIFormalities,hr.traineeNDAFormalities,hr.traineeMarksCardDetails,hr.traineeBioMetricStatus,hr.traineeICards,hr.traineeRemarks,master.traineeName,master.traineeEmailId,master.traineeMobileNum,master.traineeStatus,master.traineeYearOfExp) from BenchUnitData bench, HrUnitData hr,TraineeData master where hr.traineeData.id = master.id and bench.traineeData.id = master.id and hr.traineeBioMetricStatus= :hrTraineeBioMetricStatus")
    List<HrUnitResponse> getHrDataByTraineeBioMetricStatus(String hrTraineeBioMetricStatus);

    @Query("select new com.tyssSpark.recrutounitservice.dto.HrUnitResponse(bench.benMonth,bench.benSource,bench.benGender,bench.benBench,bench.benBatch,bench.benTraineeDuration,bench.benSkillSet,bench.benCtc,bench.benRevicedCtc,bench.benRemarks,hr.traineeOfficialId,hr.traineeOnBoardingDate,hr.hrName,hr.traineeDOB,hr.traineeFatherName,hr.traineeLocation,hr.traineeOfficialMailId,hr.traineePermanentAddress,hr.traineeJoiningFormalities,hr.traineeLOIFormalities,hr.traineeNDAFormalities,hr.traineeMarksCardDetails,hr.traineeBioMetricStatus,hr.traineeICards,hr.traineeRemarks,master.traineeName,master.traineeEmailId,master.traineeMobileNum,master.traineeStatus,master.traineeYearOfExp) from BenchUnitData bench, HrUnitData hr,TraineeData master where hr.traineeData.id = master.id and bench.traineeData.id = master.id and hr.traineeICards= :hrTraineeIcards")
    List<HrUnitResponse> getHrDataByTraineeIcards(String hrTraineeIcards);
}
